services:
  db:
    image: postgres:17
    container_name: etl_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wine_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: etl_app
    depends_on:
      - db

volumes:
  pgdata:
